### ISSUE TITLE
operator term to subset statistics?

### ISSUE THREAD

**Issue by chad-klumb** [statnet/tergm#19]
Currently, offsets are allowed in the EGMME `targets` formula specified by the user.  Since we don't want to include offset statistics in the EGMME targets proper, we attempt to remove them with the following line of code:

https://github.com/statnet/tergm/blob/941db246f136b9ff6f710cb39a3fa830dde91270/R/tergm.EGMME.R#L42

I assume this was originally done so that something like `targets = "formation"` would work even if the formation formula included offsets.  Since the `targets` formula is also used for the `san` run, and `san` now respects offsets, we have another reason to keep allowing offsets in the `targets` formula.

However, with the advent of partial offsets, operator offsets, and operator terms more generally, removing offset statistics from a model is no longer as simple as the above line of code suggests.

We could remove offset statistics from the `targets` model by wrapping the `targets` formula in an operator term that allows inclusion/exclusion of specified statistics (via a `levels`-type argument), in this case retaining those statistics that are not offsets according to `model$etamap$offsetmap`.

**Comment by chad-klumb** [comment]
This may be more important now with changes to formula extraction (offsets in formation/dissolution get buried inside other operators during extraction, so the naive code doesn't work even in "simple" cases).

I think this should be a very simple operator to actually implement (may be able to piggyback on an existing one).

**Comment by krivit** [comment]
Yes, better to filter the offsets from the monitoring model later in the process.
