### ISSUE TITLE
remove formulas from tergm simulation return values?

### ISSUE THREAD

**Issue by chad-klumb** [statnet/tergm#21]
Currently, `tergm` `simulate` functions attach (generative, constraints, and monitoring) formulas to their return values, such as here:

https://github.com/statnet/tergm/blob/78d9845a71b345d0319af8defe13aa2d52b43d2c/R/simulate.tergm.R#L426-L435

This practice can lead to memory problems, as has previously been discussed in the `ergm` context, although the problem is likely bigger here, as repeated calls to temporal `simulate` functions are not uncommon, and can lead to hierarchies of `network` inside `formula` inside `network` inside `formula` inside `network` inside ... (this was at issue in statnet/EpiModel#523).

The basic problem is not new in 4.0.  For example, the script

```
require(tergm)

nw <- network.initialize(1e5, dir = F)

sizes_with_attrs <- list()
sizes_without_attrs <- list()

for(i in 1:10) {
  nw <- simulate(nw,
                 formation = ~edges,
                 dissolution = ~edges,
                 coef.form = c(-18),
                 coef.diss = c(5),
                 output = "final")
  sizes_with_attrs[[i]] <- lobstr::obj_size(nw)
  nw_no_attr <- nw
  attributes(nw_no_attr) <- attributes(nw_no_attr)[c("names", "class")]
  sizes_without_attrs[[i]] <- lobstr::obj_size(nw_no_attr)
}

sizes_with_attrs
sizes_without_attrs
```

demonstrates excessive memory usage with both CRAN and master package versions.  (The formulas are attached to the return value as attributes.)

Currently the formula attributes are used by `tergm` in a couple of distinct ways:

- they serve as default values for the `networkDynamic` methods

https://github.com/statnet/tergm/blob/78d9845a71b345d0319af8defe13aa2d52b43d2c/R/simulate.stergm.R#L241-L251

and

https://github.com/statnet/tergm/blob/78d9845a71b345d0319af8defe13aa2d52b43d2c/R/simulate.tergm.R#L505-L513

(but not the `network` methods)

- they are used for determining whether statistics should be appended to an existing statistics attribute, in the `networkDynamic` method

https://github.com/statnet/tergm/blob/78d9845a71b345d0319af8defe13aa2d52b43d2c/R/simulate.tergm.R#L584

and

https://github.com/statnet/tergm/blob/78d9845a71b345d0319af8defe13aa2d52b43d2c/R/simulate.tergm.R#L586

(but not the `network` methods)

I'm in favor of stripping the formulas entirely and removing the above uses from the `tergm` code.  This is not fully backwards compatible, but it shouldn't be too hard to adjust to the changes (if anyone was actually relying on these things), and the alternative of leaving the formulas in does not seem acceptable.

@krivit @martinamorris @smjenness @sgoodreau 

objections?

**Comment by krivit** [comment]
If a formula is intended for purely decorative purposes, we can strip its environment, replacing it with `emptyenv()` or similar, though it could result in some cryptic error messages.

**Comment by chad-klumb** [comment]
The default arguments would require their environments to function properly.

The `==` test for stats `rbind`ing does not look at environments, but this is basically a bug rather than something to be preserved, because two formulas with different environments will not in general imply the same statistics even if they are `==`.

All things considered I think we should just get rid of this stuff.  The additional burden on the user (to actually specify the formulas they want to use, or to `rbind` the stats if they want a cumulative history) is minimal.

**Comment by chad-klumb** [comment]
I'll remove these things later this week unless someone strongly objects before then.
