### ISSUE TITLE
`attr` does partial matching by default

### ISSUE THREAD

**Issue by chad-klumb** [statnet/tergm#22]
This can lead to e.g. `attr(sim, "stats")` matching to `attr(sim, "stats.gen")` (or `"stats.form"`/`"stats.diss"` in CRAN version) in the `simulate` functions, which can lead to output that is not completely correct.

Uses of `attr` (throughout the package) should be reviewed for this pitfall and updated accordingly.  It appears that the `exact` argument to `attr` can be used to prohibit partial matching.

**Comment by krivit** [comment]
The quickest solution is to have `statnet.common` export `attr` with a different default and make sure it's imported.

Package `xfun` already exports a function like that, but I don't think it's worth adding a dependency just for that one purpose.

**Comment by krivit** [comment]
Alternatively, we could import `rlang` and use their `%@%` operation to access attributes.

**Comment by chad-klumb** [comment]
I guess re-defining `attr` would be quickest; is the intent to use this across `statnet` packages?

**Comment by krivit** [comment]
Yes. Partial matching is one of those things that are convenient for interactive use but terrible for programming.

**Comment by krivit** [comment]
Also, to be clear, are we mainly concerned about the end-user hitting this pitfall, or about our internal code?

For the former, the best we can do is rename the attributes to have no common prefixes; for the latter, we can add the function to `statnet.common`.

**Comment by chad-klumb** [comment]
internal code
