### ISSUE TITLE
review new tergm proposal code before release

### ISSUE THREAD

**Issue by chad-klumb** [statnet/tergm#24]
`tergm` version of statnet/ergm#307

almost all of the R code, many of the C data structures, and some of the C functions are re-used from `ergm`, but there are still ~500 lines of new proposal code in `tergm` (which is much less than there used to be!)

- [ ] `R/InitErgmConstraint.hints.R`
- [ ] `R/InitErgmProposal.DynMoMe.R`
- [ ] `R/zzz.R` (proposal table entries for `discordTNT` and `discordBDStratTNT`)
- [ ] `src/discordTNT.c`

tests are in `tests/testthat/test-discord-proposals.R`.

**Comment by krivit** [comment]
@chad-klumb , any updates on this?

**Comment by chad-klumb** [comment]
as reviewed as they're going to get in the immediate future
