### ISSUE TITLE
is this an incorrect implementation of the EDA?

### ISSUE THREAD

**Issue by chad-klumb** [statnet/tergm#26]
My understanding is that the dissolution coefficient should be `log(D - 1)` where `D` is the target duration, but the current implementation in `tergm` uses

https://github.com/statnet/tergm/blob/ec6170096225df22691bcc0cb9bbce5d11451b78/R/tergm.EGMME.initialfit.R#L55

Should it not be `log(mean.age - 1)`?

**Comment by krivit** [comment]
Can `mean.age` be less than 1?

**Comment by chad-klumb** [comment]
Not in my book, and I believe that's supported by conventions in papers and other code.

In the limit of zero persistence (mean age 1) you want the dissolution edges coefficient to be `-Inf`, which is handled correctly by `log(D - 1)` but not `log(D + 1)`.

**Comment by martinamorris** [comment]
Hmm.  Makes no sense.  It's always been `ln(D-1)`, until Chad proved it should be `ln(D)`.

And mean age is strictly positive (unless you haven't cleaned your data properly).

Question:  does this mean EpiModel has unknowingly been using `ln(D+1)` all this time?

**Comment by chad-klumb** [comment]
I think EpiModel is fine, e.g. if you combine this line

https://github.com/statnet/EpiModel/blob/daae94bcbd24b17f556d79b34a855159d5794bbf/R/net.utils.R#L394

with this line

https://github.com/statnet/EpiModel/blob/daae94bcbd24b17f556d79b34a855159d5794bbf/R/net.utils.R#L404

you get `log(D - 1)`.

It also uses the convention that duration must be at least 1

https://github.com/statnet/EpiModel/blob/daae94bcbd24b17f556d79b34a855159d5794bbf/R/net.utils.R#L355-L357

and it's my understanding that this has been widely adopted in the applied work (and elsewhere in `tergm`, and the original EDA paper).

**Comment by martinamorris** [comment]
thx -- i'm not surprised that `EpiModel` code is consistent with the `D-1` usage, but worried that, when `EpiModel` hands estimation over to `tergm`, this would be overwritten by `D+1` .

**Comment by chad-klumb** [comment]
The code in the OP is only run during EGMME, and only to obtain initial parameter values, so the impact on typical EpiModel use should pretty much be nil.

**Comment by krivit** [comment]
I am not sure where D+1 came from. What does the commit history say?

**Comment by chad-klumb** [comment]
https://github.com/statnet/tergm/commit/12a4e5655a77c31e8d29afed661e1cf4f5cecffd

**Comment by krivit** [comment]
Weird... What happens if we change it to mean.age-1?
