### ISSUE TITLE
Implement tests for Cross() and Change() operators in an EGMME context.

### ISSUE THREAD

**Issue by krivit** [statnet/tergm#32]
I've implemented the operators themselves, and I've added some tests for them in a CMLE context. @chad-klumb, you've implemented most of the tests for the EGMME (`dynamic=TRUE`) context.  Could you please augment them for `Cross()` and `Change()`?

**Comment by chad-klumb** [comment]
I have added `Cross` tests, and was working on `Change` tests, but ran into some unexpected behavior.

```
require(tergm)
nw <- network.initialize(10, dir = FALSE)
set.seed(0)
nws <- simulate(nw ~ edges, 
                coef = c(0), 
                dynamic = TRUE, 
                monitor = ~Change(~edges + triangle),
                output = "networkDynamic", 
                time.slices = 3)

attributes(nws)$stats

nw0 <- network.collapse(nws, at = 0)
nw1 <- network.collapse(nws, at = 1)
nw2 <- network.collapse(nws, at = 2)
nw3 <- network.collapse(nws, at = 3)

nwdiff1 <- (nw1 - nw0) + (nw0 - nw1)
nwdiff2 <- (nw2 - nw1) + (nw1 - nw2)
nwdiff3 <- (nw3 - nw2) + (nw2 - nw3)

summary(nwdiff1 ~ edges + triangle)
summary(nwdiff2 ~ edges + triangle)
summary(nwdiff3 ~ edges + triangle)
```

produces

```
> attributes(nws)$stats
Markov Chain Monte Carlo (MCMC) output:
Start = 1 
End = 3 
Thinning interval = 1 
     Change~edges Change~triangle
[1,]           20              12
[2,]           49              42
[3,]          -43            -242
```

and

```
> summary(nwdiff1 ~ edges + triangle)
   edges triangle 
      20       12 
> summary(nwdiff2 ~ edges + triangle)
   edges triangle 
      25       21 
> summary(nwdiff3 ~ edges + triangle)
   edges triangle 
      17        5 
```

So, the first row matches expectations, but not the second or third row.

@krivit is this a bug or am I misunderstanding the term's intended function?

**Comment by chad-klumb** [comment]
My interpretation of the documentation is that `Change` will evaluate its submodel on the network whose edges are precisely those dyads that have changed state between the pertinent successive time steps (in the network presented to `Change`).  The documentation doesn't explicitly state that these changed dyads are treated as edges, just that the network is "constructed by taking the dyads that have changed between time steps", but I can't imagine what that would mean other than they're treated as the edges when `Change` evaluates its submodel (which would lead me to expect the above example to produce the same statistics from both methods, and for `Change` to never produce negative edges or triangle statistics).

**Comment by krivit** [comment]
Looks like a bug. I'll look into it.

**Comment by krivit** [comment]
@chad-klumb , should be fixed now. Could you please add a test?

**Comment by krivit** [comment]
Thanks!
