### ISSUE TITLE
formation/dissolution coefficient name matching

### ISSUE THREAD

**Issue by chad-klumb** [statnet/tergm#33]
`tergm` and `EpiModel` currently do some coefficient name matching to identify formation/dissolution coefficients.  The intent is to identify coefficients corresponding to terms where `Form()` or `Diss()` is the outermost "term", but may be wrapped in `offset()` or `Offset()`, and may have any sort of cross-sectional stuff going on inside (including other operator terms).

AFAIK the only possibilities match `^Form~` or `^offset(Form~` for formation coefficients, and `^Diss~` or `^offset(Diss~` for dissolution coefficients.  @krivit do you know of any other possibilities with the current implementation?

**Comment by krivit** [comment]
It could be inside another operator. All terms also now store a `$call` element which identifies the call that generated the term, which might help.

**Comment by chad-klumb** [comment]
instances inside another operator won't be recognized; in general it's not even clear that "the formation part of the formula" is well-defined, and we need to identify this in order to use e.g. the EDA

**Comment by krivit** [comment]
OK. In that case, I think the above patterns will suffice for now.

**Comment by chad-klumb** [comment]
okay I will adjust the implementation to match to those patterns and no others

**Comment by martinamorris** [comment]
Does any of this need to be aware of name change to `Persist()` ?

**Comment by krivit** [comment]
@chad-klumb , is this working now?

**Comment by chad-klumb** [comment]
should be addressed in both packages
