### ISSUE TITLE
Updating dissolution terminology in the .Rd files

### ISSUE THREAD

**Issue by martinamorris** [statnet/tergm#34]
@chad-klumb how should this be changed in `ergm-proposals.Rd`:

https://github.com/statnet/tergm/blob/e080c25bb6e4d3d7fb07db4e08abf5ece1ae99ce/man/ergm-proposals.Rd#L60-L65

Does this proposal only work with the new `Form()` and `Diss() or Persist()` operators?  Or does it work with all of the operators, so the text should be changed to something like `rather than the temporal operator networks`.

**Comment by martinamorris** [comment]
@chad-klumb this is another example that only references `Form` and `Diss()` operators.  It clearly pertains to `Persist()`.  But what about the other two operators, `Cross()` and `Change()`.  If it can't be used in a `tergm` as a generative model term at all, then we should just say that.

```
\docType{methods}
\title{Temporally-Sensitive Terms used in Exponential Family Random Graph Models}
\description{
  Unlike ordinary \code{\link[ergm]{ergm-terms}}, which take only a single
  network as an argument, the terms documented here may also take into account
  the elapsed time since each dyad in the network was last toggled.  As currently 
  implemented, such "durational" terms may not be used in the formation
  or dissolution models (whether specified separably with \code{formation} and 
  \code{dissolution} arguments in the old style, or inside \code{Form} and 
  \code{Diss} operator terms in the new style), but may be used as targets, monitors,
  or summary statistics, and may also appear as non-separable effects 
  in the generative model (necessarily specified in the new style).  The ability to 
  use these terms in the formation and dissolution models may be added in the future.
```

**Comment by krivit** [comment]
@martinamorris , are you sure? They should be there: https://github.com/statnet/tergm/blob/master/man/ergm-terms.Rd .

**Comment by martinamorris** [comment]
That's bizarre.  I don't see it in my copy on the Persist/Diss branch.  Is it possible it didn't get incorporated there?

**Comment by martinamorris** [comment]
There seems to be some inconsistency in explanations of the "durational" terms in the `ergm-terms.Rd` doc.  First it says:

https://github.com/statnet/tergm/blob/e080c25bb6e4d3d7fb07db4e08abf5ece1ae99ce/man/ergm-terms.Rd#L42-L53

But later:

https://github.com/statnet/tergm/blob/e080c25bb6e4d3d7fb07db4e08abf5ece1ae99ce/man/ergm-terms.Rd#L139-L150

So ... can these terms be used in the dissolution model or not?

**Comment by martinamorris** [comment]
forgot to reference this issue with the last two commits:  36a7992 d5d9524 

these cover all of the cases found by searching for `diss` in this branch of the repo.

**Comment by chad-klumb** [comment]
The proposal doesn't care what the generative model is, including what operator terms you do or don't use.  `rather than the temporal operator networks` sounds fine to me (although we could also just drop the parenthetical entirely).

AFAIK durational terms inside durational operators do not currently work owing to https://github.com/statnet/tergm-private/issues/121.  The remark about `edges.ageinterval` in the dissolution model is probably from an older version and should be removed.

**Comment by martinamorris** [comment]
@krivit if you confirm removal of the text above regarding use of durational terms in the model i'll go ahead and delete this.

**Comment by krivit** [comment]
So, I took a fresh look at the durational terms in operators thing, and I think I've gotten it to work in the `durational_operator` branch. I am not sure if I can make any guarantees about the absolute values of something like `Diss(~edges.ageinterval(5,10))`, but their effects on hazard seem to work more or less correctly.

``` r
library(tergm)
data(florentine)
sim <- simulate(flomarriage~Form(~edges)+Diss(~edges+edges.ageinterval(4,7)), dynamic=TRUE, output="networkDynamic", coef=c(-2,2,-1/2), time.slices=1000)
as.data.frame(sim)$duration -> dur

freq <- tabulate(dur)
surv <- rev(cumsum(rev(tabulate(dur))))
# Estimated hazard:
(haz <- setNames(freq/surv, 1:max(dur)))[1:8]
#>         1         2         3         4         5         6         7         8 
#> 0.1155316 0.1207924 0.1184144 0.1764028 0.1808213 0.1834235 0.1217300 0.1175536
# Baseline
weighted.mean(haz[-(4:6)], surv[-(4:6)])
#> [1] 0.1196702
# For edges aged 4-6 (inclusive)
weighted.mean(haz[4:6], surv[4:6])
#> [1] 0.1797554

# Theoretical hazard:
expit <- function(x) 1/(1+exp(-x))
# Baseline
1-expit(2)
#> [1] 0.1192029
# For edges aged 4-6 (inclusive)
1-expit(2-1/2)
#> [1] 0.1824255
```

<sup>Created on 2021-06-11 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by krivit** [comment]
I've added a test for formation as well (specifically, that it occurs at the correct rate), and merged the change into `master`.

**Comment by martinamorris** [comment]
discussion of durational terms continues in #42
