### ISSUE TITLE
stergm error: unrecognized control parameter

### ISSUE THREAD

**Issue by SelenaML** [statnet/tergm#45]
I am trying to run stergm and continue to get the following error regardless of the terms I choose and without changing any of the controls:
Error: Unrecognized control parameter for ‘control.ergm()’: ‘MCMC.init.maxedges’.
I have received this error before and after updating R and tergm. I also tested it with the Sampson example on the help page.

data(samplk)
samplk12 <- stergm(list(samplk1, samplk2),
                   formation=~edges,
                   dissolution=~edges,
                   estimate="CMLE")

**Comment by krivit** [comment]
Thank you for the report! We have just updated `ergm` in a way that requires an update to `tergm` and will be updating `tergm` shortly. This issues should then go away.
