### ISSUE TITLE
should Cross propagate durationality of its submodel?

### ISSUE THREAD

**Issue by chad-klumb** [statnet/tergm#57]
Currently, (the model given by) `~Cross(...)` is not durational per `is.durational` even if (the model given by) `...` is.

Should this be changed?

There are a couple of lines in the tests that would also need to change,

https://github.com/statnet/tergm/blob/6a31b5077cc767df9595325dd4de586dc0313ebe/tests/testthat/test-term-Cross.R#L149

and

https://github.com/statnet/tergm/blob/6a31b5077cc767df9595325dd4de586dc0313ebe/tests/testthat/test-term-Cross.R#L158

(remove the `!`).

**Comment by krivit** [comment]
Yes, probably.
