### ISSUE TITLE
is the ergm-terms.Rd file the main place the Operator terms are explained?

### ISSUE THREAD

**Issue by martinamorris** [statnet/tergm#61]
If so, then the `Description` really needs to be rewritten here, if not, then it's not clear why the Operators are listed here at all in an `ergm-terms` file, and they should be deleted here.

As currently structured, the `Description` refers only to the "durational" terms, with the caveat that their use in estimation is not supported.

What follows is 2 sections:

1. the Operator terms and their explanations.

2. A section with the title "Terms to represent network statistics included in the tergm package", which lists all of the "durational" terms.  that section name needs some clarification.

So:

1. It seems like we need a short paragraph in the `Description` that introduces the Operators broadly if we are going to include them in this doc, otherwise, if they are introduced/explained elsewhere, they should probably be deleted here.
2. Can we standardize the nomenclature to "durational" so that the second section is "Durational terms included in the tergm package"?

**Comment by krivit** [comment]
I don't have a strong opinion either way; operator terms are a special case of terms, so they are documented in the same file. @joycecheng's work on term indexing will probably require changing this anyway.

**Comment by martinamorris** [comment]
Ok, so for now I'll add some text in the description about the Operator terms

**Comment by martinamorris** [comment]
for this release: eac9f3beb2b9dac0bcc000f8742047af39956ec0
