### ISSUE TITLE
simulate.tergm() should accept a dynamic=FALSE argument.

### ISSUE THREAD

**Issue by krivit** [statnet/tergm#67]
As with others, it should fall back to running `simulate.ergm()`, for the conditional simulation.

**Comment by smjenness** [comment]
@chad-klumb : didn't you convert our EpiModel calls to use simulate.tergm with dynamic = FALSE to handle this?

**Comment by smjenness** [comment]
@krivit : I think this may be helpful to keep in cases where we have a cross-sectional ergm embedded within a dynamic simulation (e.g., two tergms for persistent partnerships and one ergm for a one-time partnership network).

**Comment by krivit** [comment]
@smjenness, this simulation option probably most useful for CMLE estimates, since it's just conditional ERGM simulation.
