### ISSUE TITLE
Deprecate stergm() and simulate.stergm()?

### ISSUE THREAD

**Issue by krivit** [statnet/tergm#96]
At what point should we consider removing them?

@martinamorris , @sgoodreau , @smjenness , @chad-klumb

**Comment by smjenness** [comment]
EpiModel has been updated but some users of extension packages may still be using stergm calls, so I'd give it at least 6 months.

**Comment by martinamorris** [comment]
> At what point should we consider removing them?

6 months after a deprecation notice has been set when the function is 
called.

**Comment by chad-klumb** [comment]
Sounds fine to me.
